language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
after_success:
- mvn clean cobertura:cobertura coveralls:report
notifications:
  slack:
    secure: T4iRNZIzyo2wF6STasTnxEC2AaFLlSZo93vjbmRCSCqHX5I4V9+vBxAsRaSQeZRflsOtYFXh2DkX/C6HORdiZvlKjy1WeyL9inqOQqPE0VwAwOIiV+UJ4q1pEdZ8glwd3YKsCQp4HI/LFkH9CWrY1Y1g6nxX2IU0NzN8E/sM/WWbZf/qlIRtkic2k1pxSrbAhYECkqbxE+h3lbA0f0Cu1UHG1ATFvle2o05h+O5iE4TwFOCHsOIATm/VL/2ERF0vRIXga5A9UcpEqRCNduA2PKhJqEagMb175s2MBhObQKPO/Ej/oPDv3MElZEtWM4q/XWXC5fBy6H6z/tt41gA9loJfb09ooboDWIvkLWULEOhp3dJfn27cS4jql8hkhbO3yPGJb3bF04QTUyvZljcSe6iP9cPQQfgd51VXhdkNex2FeH0iYdYJjAP7+AsMVK3JY/GmaXpr7nKpRQSYOT2k0jDuYVxU3Ubs5oYF5Q+McfxG4JNwSCyla3WGS9p88t3orBG+H6N27zcjVdRP1xa3bTWVUbXrauhL54EXkDoJIcoCxaHio/muKVxN8fgs7wWV+K6TH88rEC+uuTTKz9+Y0erpgambWa1TjSHGSm+FuEvL3UTD2xfc3gbhfRE09trFwJDbc16jwiMt9+LVMk2nJZ08/8hqVOe8qWZ9heUCWFo=
